# This is a basic workflow to help you get started with Actions

name: otherbranch 
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "heresay"

